#annotations:
#  screwdriver.cd/buildCluster: xxxxxxxxx

shared:
  image: node:latest
  environment:
    SD_ZIP_ARTIFACTS: true
    #API_URL: 192.168.x.x:9001
  annotations:
    screwdriver.cd/cpu: MICRO
    screwdriver.cd/ram: MICRO
    #screwdriver.cd/buildCluster: xxxxxxxx

jobs:
  job1:
    steps:
      - echo-api: echo $SD_API_URL
      - echo-token: echo $SD_TOKEN
      - echo-build-id: echo $SD_BUILD_ID
      #- update-meta: |
      #    curl -X 'PUT' "${SD_API_URL}/builds/${SD_BUILD_ID}" \
      #      -H 'accept: application/json' \
      #      -H "Authorization: Bearer ${SD_TOKEN}" \
      #      -H 'Content-Type: application/json' \
      #      -d '{ "meta" : { "commit" : { "message" : "bar" } } }'
      #    echo $?
      #- echo-meta: meta get status
      - update-status: |
          curl -X 'PUT' "${SD_API_URL}builds/${SD_BUILD_ID}" \
            -H 'accept: application/json' \
            -H "Authorization: Bearer ${SD_TOKEN}" \
            -H 'Content-Type: application/json' \
            -d '{ "status": "RUNNING" }'
          echo $?
      - sleep: sleep 100
